charon {
    load_modular = yes

    plugins {
        include /etc/strongswan.d/charon/*.conf

        vici {
            load = yes
            socket = unix:///run/ipsec-sentinel/gateway-b/charon.vici
        }
    }

    filelog {
        lab {
            path = /run/ipsec-sentinel/gateway-b/charon.log
            append = no
            flush_line = yes
            ike_name = yes
            default = 1
            ike = 2
            chd = 2
            cfg = 2
            knl = 2
            net = 2
        }
    }
}

charon-systemd {
    journal {
        default = -1
    }
}
