connections {
    secure-baseline {
        version = 2
        local_addrs = 192.0.2.1
        remote_addrs = 192.0.2.2
        proposals = aes256gcm16-prfsha384-ecp384
        mobike = no
        encap = no

        local {
            auth = psk
            id = gateway-a
        }

        remote {
            auth = psk
            id = gateway-b
        }

        children {
            protected-nets {
                local_ts = 10.10.0.0/24
                remote_ts = 10.20.0.0/24
                mode = tunnel
                esp_proposals = aes256gcm16-ecp384
                start_action = none
            }
        }
    }
}

secrets {
    ike-baseline {
        id-a = gateway-a
        id-b = gateway-b
        secret = "0x5d2f1fb8d6f16c4c03b43242a236c980fed7f25af725e590eafed2e38178ed50"
    }
}
