export function makeAnalysis(overrides: Record<string, unknown> = {}) {
  return {
    analysis_version: '1.0',
    schema_id: 'ipsec-sentinel.analysis/v1',
    capture: {
      path: 'runs/run_000001/full-evidence.pcap',
      format: 'PCAP',
      packet_count: 32,
      capture_bytes: 4096,
      first_timestamp_ns: 1_000_000_000,
      last_timestamp_ns: 3_000_000_000,
      duration_seconds: 2,
      warnings: [],
    },
    summary: { status: 'COMPLETE', ipsec: 'DETECTED', message: 'Analysis completed without payload decryption.' },
    peers: {
      initiator: '192.0.2.1',
      responder: '192.0.2.2',
      peer_pairs: [['192.0.2.1', '192.0.2.2']],
      multiple_sessions: false,
    },
    protocols: {
      ipsec_detected: true,
      ike_detected: true,
      ike_version: 'IKEv2',
      esp_detected: true,
      ah_detected: false,
      natt_detected: false,
      ike_packets: 8,
      esp_packets: 24,
      ah_packets: 0,
      natt_packets: 0,
      peer_pairs: [['192.0.2.1', '192.0.2.2']],
    },
    ike: {
      detected: true,
      version: 'IKEv2',
      exchanges: [],
      initiator_spi: '0x0102030405060708',
      responder_spi: '0x1112131415161718',
      encryption: { raw: 'ENCR_AES_GCM_16/256', normalized: 'AES-256-GCM', provenance: 'OBSERVED', evidence_id: 'ev-cipher' },
      integrity: { raw: 'NONE', normalized: 'AEAD', provenance: 'OBSERVED' },
      prf: { raw: 'PRF_HMAC_SHA2_384', normalized: 'HMAC-SHA-384', provenance: 'OBSERVED' },
      dh_group: { raw: 'ECP_384', normalized: 'ECP-384', provenance: 'OBSERVED' },
      selection_basis: 'RESPONDER_SELECTED',
      traffic_selectors: { value: 'UNKNOWN', provenance: 'UNKNOWN' },
    },
    controlled_evidence: { available: true, source: 'dataset-run' },
    security_associations: [{
      sa_type: 'ESP_CHILD_SA',
      source: '192.0.2.1',
      destination: '192.0.2.2',
      spi: '0x00000001',
      first_packet_number: 9,
      first_timestamp_ns: 1_400_000_000,
      packet_count: 12,
      unique_packet_count: 12,
      bytes: 2048,
      predecessor_spi: null,
      successor_spi: '0x00000003',
      rekey_provenance: 'DERIVED',
      rekey_evidence_id: 'ev-rekey',
      pfs: { state: 'unknown', provenance: 'UNKNOWN' },
    }],
    pfs: { state: 'enabled', provenance: 'DERIVED', evidence_ids: ['ev-pfs'], explanation: 'Fresh CHILD-SA DH behavior verifies PFS.' },
    esp: {
      packet_count: 24,
      bytes: 30720,
      duration_seconds: 2,
      direction_counts: { forward: 14, reverse: 10 },
      direction_bytes: { forward: 19000, reverse: 11720 },
      spi_distribution: { '0x00000001': 12, '0x00000002': 12 },
      peer_pair: ['192.0.2.1', '192.0.2.2'],
      features: { packet_count: 24, packet_rate: 12, burst_count: 5, size_mean: 1280 },
      feature_schema_version: 'ipsec-sentinel.esp-session-features/v1',
      payload_decrypted: false,
    },
    traffic_intelligence: {
      state: 'PREDICTED',
      predicted_class: 'video',
      raw_confidence: 0.964,
      confidence_kind: 'raw_uncalibrated',
      probabilities: { video: 0.964, web: 0.036 },
      provenance: 'AI_INFERRED',
      model_version: 'ipsec-sentinel.classifier/v1',
      feature_schema_version: 'ipsec-sentinel.esp-session-features/v1',
      payload_decrypted: false,
      reason: null,
    },
    evidence: [
      { id: 'ev-cipher', provenance: 'OBSERVED', description: 'Responder-selected transform', packet_numbers: [4, 5], timestamps_ns: [1_100_000_000, 1_200_000_000], protocol: 'IKEv2', raw_value: 'ENCR_AES_GCM_16/256', normalized_value: 'AES-256-GCM', source_component: 'ike-analyzer', confidence: null },
      { id: 'ev-pfs', provenance: 'DERIVED', description: 'Fresh CHILD-SA DH selected during rekey', packet_numbers: [], timestamps_ns: [], protocol: 'IKEv2', raw_value: 'ECP_384', normalized_value: 'enabled', source_component: 'controlled-evidence', confidence: null },
      { id: 'ev-rekey', provenance: 'DERIVED', description: 'ESP SPI replacement observed', packet_numbers: [9, 21], timestamps_ns: [1_400_000_000, 2_400_000_000], protocol: 'ESP', raw_value: '0x00000001', normalized_value: '0x00000003', source_component: 'sa-reconstructor', confidence: null },
      { id: 'ev-traffic', provenance: 'AI_INFERRED', description: 'Traffic classified from ESP behavior', packet_numbers: [], timestamps_ns: [], protocol: 'ESP', raw_value: 'video', normalized_value: 'video', source_component: 'ml-classifier', confidence: 0.964 },
    ],
    findings: [
      { rule_id: 'IPSEC-CRYPTO-001', title: 'Modern AEAD encryption', severity: 'INFO', status: 'PASS', provenance: 'OBSERVED', summary: 'AES-256-GCM was selected.', technical_explanation: 'GCM provides authenticated encryption.', impact: 'Modern confidentiality and integrity.', recommendation: 'Retain an approved GCM configuration.', evidence_ids: ['ev-cipher'] },
      { rule_id: 'IPSEC-PFS-001', title: 'CHILD-SA PFS verified', severity: 'INFO', status: 'PASS', provenance: 'DERIVED', summary: 'Fresh CHILD-SA DH behavior verifies PFS.', technical_explanation: 'A fresh DH exchange was observed.', impact: 'Past session keys do not expose rekeyed traffic.', recommendation: 'Retain CHILD-SA PFS.', evidence_ids: ['ev-pfs'] },
    ],
    security_score: {
      total: 96,
      maximum: 100,
      assessed_weight: 82,
      unassessed_weight: 18,
      method: 'normalized over assessed evidence; UNKNOWN is not penalized',
      categories: [
        { name: 'Cryptography', maximum_score: 30, achieved_score: 30, assessed_weight: 30, unassessed_weight: 0, deductions: [] },
        { name: 'Key Exchange / PFS', maximum_score: 25, achieved_score: 25, assessed_weight: 25, unassessed_weight: 0, deductions: [] },
        { name: 'Security Association Hygiene', maximum_score: 15, achieved_score: 10, assessed_weight: 10, unassessed_weight: 5, deductions: [] },
        { name: 'Replay / Protocol Protections', maximum_score: 15, achieved_score: 5, assessed_weight: 5, unassessed_weight: 10, deductions: [] },
        { name: 'Metadata / Privacy Exposure', maximum_score: 15, achieved_score: 12, assessed_weight: 12, unassessed_weight: 3, deductions: [] },
      ],
    },
    limitations: [{ code: 'NO_DECRYPTION', description: 'ESP payloads were not decrypted.' }],
    ...overrides,
  }
}

export function makeEnvelope(analysis = makeAnalysis()) {
  return {
    analysis,
    xray: {
      schema_id: 'ipsec-sentinel.xray/v1',
      version: '1.0',
      total_packet_count: 24,
      displayed_packet_count: 3,
      sampled: true,
      duration_seconds: 2,
      peer_pair: ['192.0.2.1', '192.0.2.2'],
      packets: [
        { relative_time_seconds: 0, length: 92, direction: 'forward' },
        { relative_time_seconds: 1, length: 1180, direction: 'forward' },
        { relative_time_seconds: 2, length: 188, direction: 'reverse' },
      ],
    },
  }
}

